mv al_2w_layer_1.ref ../../tran/prop/. 
mv al_2w_layer_2.ref ../../tran/prop/. 
mv al_2w_layer_3.ref ../../tran/prop/. 
mv al_2w_layer_4.ref ../../tran/prop/. 
mv al_2w_layer_5.ref ../../tran/prop/. 
mv al_2w_layer_6.ref ../../tran/prop/. 
mv al_2w_layer_7.ref ../../tran/prop/. 
mv botm_layer_1.ref ../../flow/geo_/. 
mv botm_layer_2.ref ../../flow/geo_/. 
mv botm_layer_3.ref ../../flow/geo_/. 
mv botm_layer_4.ref ../../flow/geo_/. 
mv botm_layer_5.ref ../../flow/geo_/. 
mv botm_layer_6.ref ../../flow/geo_/. 
mv botm_layer_7.ref ../../flow/geo_/. 
mv chdp ../../flow/bcnd/. 
mv ctet_eff.txt ../../tran/base/. 
mv ctet_mass_extracted_kg.csv ../../tran/base/. 
mv ctet_mass_ext_raw.csv ../../tran/base/. 
mv cts_wells.csv ../../tran/base/. 
mv delc.ref ../../flow/geo_/. 
mv delr.ref ../../flow/geo_/. 
mv dmcoef1.ref ../../tran/rect/. 
mv dz_layer_1.ref ../../tran/geo_/. 
mv dz_layer_2.ref ../../tran/geo_/. 
mv dz_layer_3.ref ../../tran/geo_/. 
mv dz_layer_4.ref ../../tran/geo_/. 
mv dz_layer_5.ref ../../tran/geo_/. 
mv dz_layer_6.ref ../../tran/geo_/. 
mv dz_layer_7.ref ../../tran/geo_/. 
mv hk_Layer_1.ref ../../flow/prop/. 
mv hk_Layer_2.ref ../../flow/prop/. 
mv hk_Layer_3.ref ../../flow/prop/. 
mv hk_Layer_4.ref ../../flow/prop/. 
mv hk_Layer_5.ref ../../flow/prop/. 
mv hk_Layer_6.ref ../../flow/prop/. 
mv hk_Layer_7.ref ../../flow/prop/. 
mv hk_Layer_8.ref ../../flow/prop/. 
mv htop.ref ../../flow/geo_/. 
mv i129_plume_targs.csv ../../tran/base/. 
mv ibound_layer_1.ref ../../flow/geo_/. 
mv ibound_layer_2.ref ../../flow/geo_/. 
mv ibound_layer_3.ref ../../flow/geo_/. 
mv ibound_layer_4.ref ../../flow/geo_/. 
mv ibound_layer_5.ref ../../flow/geo_/. 
mv ibound_layer_6.ref ../../flow/geo_/. 
mv ibound_layer_7.ref ../../flow/geo_/. 
mv icbund_layer_1.ref ../../tran/geo_/. 
mv icbund_layer_2.ref ../../tran/geo_/. 
mv icbund_layer_3.ref ../../tran/geo_/. 
mv icbund_layer_4.ref ../../tran/geo_/. 
mv icbund_layer_5.ref ../../tran/geo_/. 
mv icbund_layer_6.ref ../../tran/geo_/. 
mv icbund_layer_7.ref ../../tran/geo_/. 
mv mod2tec ../../flow/base/. 
mv model_top.ref ../../flow/geo_/. 
mv P2RGWM.adv ../../tran/mt3d/. 
mv P2RGWM.btn ../../tran/mt3d/. 
mv P2RGWM.cnf ../../tran/mt3d/. 
mv P2RGWM.cts ../../tran/mt3d/. 
mv P2RGWM.dsp ../../tran/mt3d/. 
mv P2RGWM.gcg ../../tran/mt3d/. 
mv P2RGWM.hss ../../tran/hssm/. 
mv P2RGWM.m3d ../../tran/mt3d/. 
mv P2RGWM.mas ../../tran/mt3d/. 
mv P2RGWM.nam ../../tran/mt3d/. 
mv P2RGWM.obs ../../tran/mt3d/. 
mv P2RGWM.rct ../../tran/rect/. 
mv P2RGWM.ssm ../../tran/hssm/. 
mv P2Rv8.3.mnw2 ../../flow/bcnd/. 
mv P2Rv9.1_2W.spc ../../flow/base/. 
mv P2W_msft_91.bas ../../flow/base/. 
mv P2W_msft_91.bcf ../../flow/base/. 
mv P2Wv9.1_ato.oc ../../flow/base/. 
mv P2Wv9.1.bas ../../flow/base/. 
mv P2Wv9.1.BYND_out ../../flow/base/. 
mv P2Wv9.1.chd ../../flow/bcnd/. 
mv P2Wv9.1.chk ../../flow/base/. 
mv P2Wv9.1.ddn ../../flow/base/. 
mv P2Wv9.1.dis ../../flow/geo_/. 
mv P2Wv9.1_init.hds ../../flow/base/. 
mv P2Wv9.1.lmt ../../flow/base/. 
mv P2Wv9.1.lpf ../../flow/prop/. 
mv P2Wv9.1.lst ../../flow/base/. 
mv P2Wv9.1.mnw2 ../../flow/bcnd/. 
mv P2Wv9.1.mnwi ../../flow/bcnd/. 
mv P2Wv9.1.mst ../../flow/base/. 
mv P2Wv9.1.nam ../../flow/base/. 
mv P2Wv9.1.ort ../../flow/base/. 
mv P2Wv9.1.QSUM_out ../../flow/base/. 
mv P2Wv9.1.rch ../../flow/bcnd/. 
mv P2Wv9.1.spc ../../flow/base/. 
mv P2Wv9.1.tso ../../flow/base/. 
mv P2Wv9.1.WEL1_out ../../flow/base/. 
mv prsity_layer_1.ref ../../tran/prop/. 
mv prsity_layer_2.ref ../../tran/prop/. 
mv prsity_layer_3.ref ../../tran/prop/. 
mv prsity_layer_4.ref ../../tran/prop/. 
mv prsity_layer_5.ref ../../tran/prop/. 
mv prsity_layer_6.ref ../../tran/prop/. 
mv prsity_layer_7.ref ../../tran/prop/. 
mv prsity_layer_8.ref ../../tran/prop/. 
mv rc11_layer_1.ref ../../tran/rect/. 
mv rc11_layer_2.ref ../../tran/rect/. 
mv rc11_layer_3.ref ../../tran/rect/. 
mv rc11_layer_4.ref ../../tran/rect/. 
mv rc11_layer_5.ref ../../tran/rect/. 
mv rc11_layer_6.ref ../../tran/rect/. 
mv rc11_layer_7.ref ../../tran/rect/. 
mv rc21_layer_1.ref ../../tran/rect/. 
mv rc21_layer_2.ref ../../tran/rect/. 
mv rc21_layer_3.ref ../../tran/rect/. 
mv rc21_layer_4.ref ../../tran/rect/. 
mv rc21_layer_5.ref ../../tran/rect/. 
mv rc21_layer_6.ref ../../tran/rect/. 
mv rc21_layer_7.ref ../../tran/rect/. 
mv rech_0.ref ../../flow/bcnd/. 
mv rech_100.ref ../../flow/bcnd/. 
mv rech_101.ref ../../flow/bcnd/. 
mv rech_102.ref ../../flow/bcnd/. 
mv rech_103.ref ../../flow/bcnd/. 
mv rech_104.ref ../../flow/bcnd/. 
mv rech_105.ref ../../flow/bcnd/. 
mv rech_106.ref ../../flow/bcnd/. 
mv rech_107.ref ../../flow/bcnd/. 
mv rech_108.ref ../../flow/bcnd/. 
mv rech_109.ref ../../flow/bcnd/. 
mv rech_10.ref ../../flow/bcnd/. 
mv rech_110.ref ../../flow/bcnd/. 
mv rech_111.ref ../../flow/bcnd/. 
mv rech_112.ref ../../flow/bcnd/. 
mv rech_113.ref ../../flow/bcnd/. 
mv rech_114.ref ../../flow/bcnd/. 
mv rech_115.ref ../../flow/bcnd/. 
mv rech_116.ref ../../flow/bcnd/. 
mv rech_117.ref ../../flow/bcnd/. 
mv rech_118.ref ../../flow/bcnd/. 
mv rech_119.ref ../../flow/bcnd/. 
mv rech_11.ref ../../flow/bcnd/. 
mv rech_120.ref ../../flow/bcnd/. 
mv rech_12.ref ../../flow/bcnd/. 
mv rech_13.ref ../../flow/bcnd/. 
mv rech_14.ref ../../flow/bcnd/. 
mv rech_15.ref ../../flow/bcnd/. 
mv rech_16.ref ../../flow/bcnd/. 
mv rech_17.ref ../../flow/bcnd/. 
mv rech_18.ref ../../flow/bcnd/. 
mv rech_19.ref ../../flow/bcnd/. 
mv rech_1.ref ../../flow/bcnd/. 
mv rech_20.ref ../../flow/bcnd/. 
mv rech_21.ref ../../flow/bcnd/. 
mv rech_22.ref ../../flow/bcnd/. 
mv rech_23.ref ../../flow/bcnd/. 
mv rech_24.ref ../../flow/bcnd/. 
mv rech_25.ref ../../flow/bcnd/. 
mv rech_26.ref ../../flow/bcnd/. 
mv rech_27.ref ../../flow/bcnd/. 
mv rech_28.ref ../../flow/bcnd/. 
mv rech_29.ref ../../flow/bcnd/. 
mv rech_2.ref ../../flow/bcnd/. 
mv rech_30.ref ../../flow/bcnd/. 
mv rech_31.ref ../../flow/bcnd/. 
mv rech_32.ref ../../flow/bcnd/. 
mv rech_33.ref ../../flow/bcnd/. 
mv rech_34.ref ../../flow/bcnd/. 
mv rech_35.ref ../../flow/bcnd/. 
mv rech_36.ref ../../flow/bcnd/. 
mv rech_37.ref ../../flow/bcnd/. 
mv rech_38.ref ../../flow/bcnd/. 
mv rech_39.ref ../../flow/bcnd/. 
mv rech_3.ref ../../flow/bcnd/. 
mv rech_40.ref ../../flow/bcnd/. 
mv rech_41.ref ../../flow/bcnd/. 
mv rech_42.ref ../../flow/bcnd/. 
mv rech_43.ref ../../flow/bcnd/. 
mv rech_44.ref ../../flow/bcnd/. 
mv rech_45.ref ../../flow/bcnd/. 
mv rech_46.ref ../../flow/bcnd/. 
mv rech_47.ref ../../flow/bcnd/. 
mv rech_48.ref ../../flow/bcnd/. 
mv rech_49.ref ../../flow/bcnd/. 
mv rech_4.ref ../../flow/bcnd/. 
mv rech_50.ref ../../flow/bcnd/. 
mv rech_51.ref ../../flow/bcnd/. 
mv rech_52.ref ../../flow/bcnd/. 
mv rech_53.ref ../../flow/bcnd/. 
mv rech_54.ref ../../flow/bcnd/. 
mv rech_55.ref ../../flow/bcnd/. 
mv rech_56.ref ../../flow/bcnd/. 
mv rech_57.ref ../../flow/bcnd/. 
mv rech_58.ref ../../flow/bcnd/. 
mv rech_59.ref ../../flow/bcnd/. 
mv rech_5.ref ../../flow/bcnd/. 
mv rech_60.ref ../../flow/bcnd/. 
mv rech_61.ref ../../flow/bcnd/. 
mv rech_62.ref ../../flow/bcnd/. 
mv rech_63.ref ../../flow/bcnd/. 
mv rech_64.ref ../../flow/bcnd/. 
mv rech_65.ref ../../flow/bcnd/. 
mv rech_66.ref ../../flow/bcnd/. 
mv rech_67.ref ../../flow/bcnd/. 
mv rech_68.ref ../../flow/bcnd/. 
mv rech_69.ref ../../flow/bcnd/. 
mv rech_6.ref ../../flow/bcnd/. 
mv rech_70.ref ../../flow/bcnd/. 
mv rech_71.ref ../../flow/bcnd/. 
mv rech_72.ref ../../flow/bcnd/. 
mv rech_73.ref ../../flow/bcnd/. 
mv rech_74.ref ../../flow/bcnd/. 
mv rech_75.ref ../../flow/bcnd/. 
mv rech_76.ref ../../flow/bcnd/. 
mv rech_77.ref ../../flow/bcnd/. 
mv rech_78.ref ../../flow/bcnd/. 
mv rech_79.ref ../../flow/bcnd/. 
mv rech_7.ref ../../flow/bcnd/. 
mv rech_80.ref ../../flow/bcnd/. 
mv rech_81.ref ../../flow/bcnd/. 
mv rech_82.ref ../../flow/bcnd/. 
mv rech_83.ref ../../flow/bcnd/. 
mv rech_84.ref ../../flow/bcnd/. 
mv rech_85.ref ../../flow/bcnd/. 
mv rech_86.ref ../../flow/bcnd/. 
mv rech_87.ref ../../flow/bcnd/. 
mv rech_88.ref ../../flow/bcnd/. 
mv rech_89.ref ../../flow/bcnd/. 
mv rech_8.ref ../../flow/bcnd/. 
mv rech_90.ref ../../flow/bcnd/. 
mv rech_91.ref ../../flow/bcnd/. 
mv rech_92.ref ../../flow/bcnd/. 
mv rech_93.ref ../../flow/bcnd/. 
mv rech_94.ref ../../flow/bcnd/. 
mv rech_95.ref ../../flow/bcnd/. 
mv rech_96.ref ../../flow/bcnd/. 
mv rech_97.ref ../../flow/bcnd/. 
mv rech_98.ref ../../flow/bcnd/. 
mv rech_99.ref ../../flow/bcnd/. 
mv rech_9.ref ../../flow/bcnd/. 
mv rhob_layer_1.ref ../../tran/prop/. 
mv rhob_layer_2.ref ../../tran/prop/. 
mv rhob_layer_3.ref ../../tran/prop/. 
mv rhob_layer_4.ref ../../tran/prop/. 
mv rhob_layer_5.ref ../../tran/prop/. 
mv rhob_layer_6.ref ../../tran/prop/. 
mv rhob_layer_7.ref ../../tran/prop/. 
mv rhob_layer_8.ref ../../tran/prop/. 
mv sconc1_layer_1.ref ../../tran/icnc/. 
mv sconc1_layer_2.ref ../../tran/icnc/. 
mv sconc1_layer_3.ref ../../tran/icnc/. 
mv sconc1_layer_4.ref ../../tran/icnc/. 
mv sconc1_layer_5.ref ../../tran/icnc/. 
mv sconc1_layer_6.ref ../../tran/icnc/. 
mv sconc1_layer_7.ref ../../tran/icnc/. 
mv settings.fig ../../flow/base/. 
mv sim_equiv_mass_ext.csv ../../flow/base/. 
mv sim_equiv_mass_ext_empty.csv ../../flow/base/. 
mv sp11_layer_1.ref ../../tran/rect/. 
mv sp11_layer_2.ref ../../tran/rect/. 
mv sp11_layer_3.ref ../../tran/rect/. 
mv sp11_layer_4.ref ../../tran/rect/. 
mv sp11_layer_5.ref ../../tran/rect/. 
mv sp11_layer_6.ref ../../tran/rect/. 
mv sp11_layer_7.ref ../../tran/rect/. 
mv sp21_layer_1.ref ../../tran/rect/. 
mv sp21_layer_2.ref ../../tran/rect/. 
mv sp21_layer_3.ref ../../tran/rect/. 
mv sp21_layer_4.ref ../../tran/rect/. 
mv sp21_layer_5.ref ../../tran/rect/. 
mv sp21_layer_6.ref ../../tran/rect/. 
mv sp21_layer_7.ref ../../tran/rect/. 
mv ss_Layer_1.ref ../../flow/prop/. 
mv ss_Layer_2.ref ../../flow/prop/. 
mv ss_Layer_3.ref ../../flow/prop/. 
mv ss_Layer_4.ref ../../flow/prop/. 
mv ss_Layer_5.ref ../../flow/prop/. 
mv ss_Layer_6.ref ../../flow/prop/. 
mv ss_Layer_7.ref ../../flow/prop/. 
mv ss_Layer_8.ref ../../flow/prop/. 
mv strt_layer_1.ref ../../flow/base/. 
mv strt_layer_2.ref ../../flow/base/. 
mv strt_layer_3.ref ../../flow/base/. 
mv strt_layer_4.ref ../../flow/base/. 
mv strt_layer_5.ref ../../flow/base/. 
mv strt_layer_6.ref ../../flow/base/. 
mv strt_layer_7.ref ../../flow/base/. 
mv strt_layer_8.ref ../../flow/base/. 
mv sy_Layer_1.ref ../../flow/prop/. 
mv sy_Layer_2.ref ../../flow/prop/. 
mv sy_Layer_3.ref ../../flow/prop/. 
mv sy_Layer_4.ref ../../flow/prop/. 
mv sy_Layer_5.ref ../../flow/prop/. 
mv sy_Layer_6.ref ../../flow/prop/. 
mv sy_Layer_7.ref ../../flow/prop/. 
mv sy_Layer_8.ref ../../flow/prop/. 
mv trpt.ref ../../tran/base/. 
mv trpv.ref ../../tran/base/. 
mv vka1.ref ../../flow/prop/. 
mv vka2.ref ../../flow/prop/. 
mv vka3.ref ../../flow/prop/. 
mv vka4.ref ../../flow/prop/. 
mv vka5.ref ../../flow/prop/. 
mv vka6.ref ../../flow/prop/. 
mv vka7.ref ../../flow/prop/. 
